/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export interface WmUser {
  create_time: Generated<Date | null>;
  id: Generated<number>;
  update_time: Generated<Date | null>;
  username: Generated<string>;
}

export interface DB {
  wm_user: WmUser;
}
